# Generated by Django 4.1.1 on 2023-04-27 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='prenom')),
                ('tel', models.IntegerField(verbose_name='telephone')),
                ('tel_pro', models.IntegerField(verbose_name='tel pro')),
                ('ldn', models.CharField(max_length=150, verbose_name='lieux de naissance')),
                ('ddn', models.DateTimeField(verbose_name='date de naissance')),
                ('nationalite', models.CharField(max_length=50, verbose_name='nationalite')),
                ('est_vivant', models.BooleanField(verbose_name='est vivant')),
                ('sexe', models.CharField(max_length=50, verbose_name='sex')),
                ('c_contact', models.IntegerField(null=True, verbose_name='contact conjoint')),
                ('c_nom', models.CharField(max_length=50, verbose_name='nom du conjoint')),
                ('C_prenom', models.CharField(max_length=50, verbose_name='prenom du conjoint')),
                ('nbr_enfant', models.IntegerField(verbose_name="nombre d'enfants")),
                ('ddmr', models.DateField(verbose_name='date de mariage')),
                ('est_mr', models.BooleanField(verbose_name='est marier')),
                ('matrcule', models.IntegerField(unique=True, verbose_name='matricune')),
                ('est_valide', models.BooleanField(verbose_name='est valide')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='account')),
            ],
        ),
    ]
